[package]
name = "loreum-distributor"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
rand_chacha = "0.2.2"
x25519-dalek = "1.2.0"
sha2 = "0.10.2"
chacha20poly1305 = "0.9.0"
rand = "0.7.0"
